# SwiftLint Config — Airbnb Custom Rules
# Source: https://github.com/airbnb/swift
# Adapted from nxt-up/nextup-ios-app

custom_rules:
  no_objcMembers:
    name: "@objcMembers"
    regex: "@objcMembers"
    message: "Explicitly use @objc on each member you want to expose to Objective-C"
    severity: error

  no_direct_standard_out_logs:
    name: "Writing log messages directly to standard out is disallowed"
    regex: "(\\bprint|\\bdebugPrint|\\bdump)\\s*\\("
    match_kinds:
      - identifier
    message: "Don't commit print()/debugPrint()/dump(). Use NSLog or os_log instead."
    severity: warning

  no_file_literal:
    name: "#file is disallowed"
    regex: "(\\b#file\\b)"
    match_kinds:
      - identifier
    message: "Instead of #file, use #fileID"
    severity: error

  no_unchecked_sendable:
    name: "`@unchecked Sendable` is discouraged"
    regex: "@unchecked Sendable"
    match_kinds:
      - attribute.builtin
      - typeidentifier
    message: "Instead of @unchecked Sendable, consider a safe alternative like standard Sendable conformance."
    severity: error
